apiVersion: v1
kind: PersistentVolume
metadata:
  name: spring
  labels:
    type: local
spec:
  storageClassName: spring
  claimRef:
    name: spring
    namespace: default
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy:
  hostPath:
    path: "/mnt/data"
