apiVersion: v1
kind: Service
metadata:
  name: spring-service
  labels:
    app: mysql-spring
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: mysql-spring
    tier: frontend
  clusterIP: 10.100.113.23
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spring
  labels:
    app: mysql-spring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: spring
  labels:
    app: mysql-spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-spring
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-spring
        tier: frontend
    spec:
      containers:
      - image: mawfia/spring:{{ .Values.version | default 1.0 }}
        name: spring
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        ports:
        - containerPort: 8080
          name: spring
        volumeMounts:
        - name: spring
          mountPath: /var/www/html
      volumes:
      - name: spring
        persistentVolumeClaim:
          claimName: spring
